#!/usr/bin/env python3
#
import sys
import re
import json
fname = sys.argv[1]


data = dict()
cellname = ""
with open(fname) as fi:
    for line in fi:

        if(re.search(r"\"name\":",line)):
            cellname = re.sub("^\s*","",line).replace("\"","").replace("\"name\":","")


        m = re.search(r"\"(x|y)\d\":\s+(\d+),?\s*$",line)
        if(m):
            n = int(int(m.groups()[1])/10)
            ns = str(n)
            if(re.search(r"(0)$",ns)):
                pass
            else:
                if(cellname not in data):
                    data[cellname] = list()
                data[cellname].append(re.sub("^\s*","",line))

print(json.dumps(data,indent=4))
